---
drake_cache: ".ui"
dependencies: "dependencies"
output:
  html_tag:
    filename: "index.html"
    dirpath: "`r library(econR); . %//% 'docs'`"
    object: "ui"
---


```{r makecondition}
library(dplyr)
library(shiny)
library(htmltools)
library(econR)
library(leaflet)
library(readr)
load("~/Documents/GitHub/medicApp/support/TW_hos.RData")
```

```{r tw_data110}
tw_data110 <- read_csv("support/\u53f0\u7063\u8cc7\u6599.csv")%>%as.list()
```

```{r dependencies}
dependencies <- {
  myown_deps <- htmltools::htmlDependency(
      name="myown",
      version="1.0.0",
      src=c(file= . %//% "assets"),
      script = "js/myscript.js",
      stylesheet="css/mystyle.css"
    )
  econR_deps <- econR::html_dependencies()
  tagList(
    econR_deps$jquery(),
    econR_deps$materialise(),
    myown_deps
  )
}
```

```{r plt_widgetConsoleLog}
plt_widget %>% 
  htmlwidgets::onRender(
    jsCode =change
  ) -> plt_widgetConsoleLog
```


```{r script}
script <- tags$script(name)
```

## =======================

### Input

```{r input_bins}
sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
```

### Output

```{r output_distPlot}
output_distPlot <- shiny::plotOutput("distPlot")
```

## =======================

### UI

```{r option_card}
option_card <- {tags$div(class="row", 
    tags$div(class="", 
      tags$div(class="card red lighten-4", 
        tags$div(class="card-content white-text",
        tags$a(class="btn red tooltipped waves-effect waves-light",
              `data-position`="top",`data-tooltip`="切換至北部","北部"),
        tags$a(class="btn red tooltipped waves-effect waves-light",
              `data-position`="top",`data-tooltip`="切換至中部","中部"),
        tags$br(),tags$br(),
        tags$a(class="btn red tooltipped waves-effect waves-light",
              `data-position`="bottom",`data-tooltip`="切換至南部","南部"),
        tags$a(class="btn red tooltipped waves-effect waves-light" , 
              `data-position`="bottom",`data-tooltip`="切換至東部","東部"),
        tags$br(),tags$br(),
        )
      )
    )
  )}
```

```{r Taiwan}
#把資料放入html
Taiwan <- {tags$script(
  id="tw_data110",
  type="application/json",
  jsonlite::toJSON(tw_data110, auto_unbox = T)
)}
```

```{r info_card}
info_card <- {tags$div(class="row",
      tags$div(
      tags$div(class="card red", 
          tags$div(class="card-content white-text", 
          tags$span(id="place",class="card-title","台灣"),
          tags$p("年度",tags$span(id="year","110"),tags$br(),
            "人口數",tags$span(id="popu","2354萬"),"人",tags$br(),
                 "護理人員數",tags$span(id="nurse","19813.74"),"人",tags$br(),
                 "護病比",tags$span(id="rate","7.0"),tags$br(),
                 "病床數",tags$span(id="bed","14萬1324"),"床")
        )
          )
      
      ))
   }
```

```{r  map_card}
 tags$div(class="row", 
    tags$div(class="col s12 m6", 
      tags$div(class="card", 
        tags$div(plt_widgetConsoleLog),
        
      )
    ),tags$div(class="col s12 m6",
               tags$div(info_card),
               tags$div(option_card))
  )
```

```{r footer}
footer <- {tags$footer(class="page-footer red lighten-1", 
          tags$div(class="container red lighten-1", 
            tags$div(class="row", 
              tags$div(class="col l6 s12", 
                tags$h5(class="white-text"," Footer Content"),
                tags$p(class="grey-text text-lighten-4","護病比")
              ),
              tags$div(class="col l4 offset-l2 s12", 
                tags$h5(class="white-text"," Links")
              )
            )
          )
        )}
```

```{r ui}
ui <- tags$body(
  tags$div(class="container",
  map_card,
  Taiwan,
  script,
  ))
```





## =======================


## Browse

```{r}
web$browse()
```


```{js}
function(map){
plt_widget = map;console.log(map);
plt_widget.on("plotly_hover",function(e){
event_data=e;
console.log(e)});
plt_widget.on("plotly_click",function(e){
$place.text(event_data.points[0].fullData.name)
});}
```



## JS

```{r setup}
library(r2d3)
```

```{r change}
change <- "function(map){
plt_widget = map;console.log(map);
plt_widget.on(\"plotly_hover\",function(e){
event_data=e;
console.log(e)});
plt_widget.on(\"plotly_click\",function(e){
$place.text(event_data.points[0].fullData.name)
});}"
```

```{r name}
name <- "$place = $(\"#place\");
$year = $(\"#year\");
$popu = $(\"#popu\");
$nurse = $(\"#nurse\");
$rate = $(\"#rate\");
$bed= $(\"#bed\");"
```



<!--JS end-->
